version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "04:00"
  open-pull-requests-limit: 10
  groups:
    eslint:
      patterns:
        - "@eslint/*"
        - "@typescript-eslint/*"
        - "eslint-*"
        - "eslint"
        - "typescript-eslint"
    react:
      patterns:
        - "@types/react"
        - "react"
        - "react-dom"
    testing-library:
      patterns:
        - "@testing-library/*"
    vitest:
      patterns:
        - "vitest"
        - "@vitest/*"
